figure('Name','Position estimate 99% confidence bounds')
hold on; plot( [conf_bound_x(:,1)' conf_bound_x(:,2)'], [ [1:4] [1:4] ],'rx')
hold on; plot( [conf_bound_y(:,1)' conf_bound_y(:,2)'], [ [1:4] [1:4] ],'gs')
hold on; plot( [ conf_bound_z(:,1)' conf_bound_z(:,2)'] , [ [1:4] [1:4] ],'bo')
% ylim( [0,0.15]  )
legend(' x','y','z')
ylabel('camera position number')
xlabel('Position estimate 99% confidence bound(m)')
ylim([0.5 4.5])
